# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='tcga-cancer-classification',
    version='0.1.0',
    description='A deep learning approach to classify cancer type from TCGA data.',
    python_requires='==3.*,>=3.6.0',
    author='André Ferreira',
    author_email='andrecnf@gmail.com',
    packages=[],
    package_data={},
    install_requires=[
        'comet-ml==2.*,>=2.0.0', 'configobj==5.*,>=5.0.0', 'dask==2.*,>=2.4.0',
        'data-utils', 'distributed==2.*,>=2.4.0', 'fastparquet==0.*,>=0.3.2',
        'fsspec==0.*,>=0.4.4', 'jinja2==2.*,>=2.10.0', 'joblib==0.*,>=0.14.1',
        'matplotlib==3.*,>=3.1.0', 'model-interpreter', 'modin==0.*,>=0.7.0',
        'numpy==1.*,>=1.17.0', 'pandas==0.*,>=0.25.1', 'pixiedust==1.*,>=1.1.0',
        'plotly==4.*,>=4.1.0', 'ray==0.*,>=0.8.1', 'scikit-learn==0.*,>=0.22.1',
        'shap==0.*,>=0.34.0', 'torch==1.*,>=1.2.0', 'tqdm==4.*,>=4.35.0',
        'xgboost==0.*,>=0.90.0'
    ],
    dependency_links=[
        'git+git@github.com:AndreCNF/data-utils.git#egg=data-utils',
        'git+git@github.com:AndreCNF/model-interpreter.git#egg=model-interpreter'
    ],
)
